# Generated by Django 5.0.6 on 2024-11-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrarusuario',
            options={'verbose_name': 'RegistrarUsuario', 'verbose_name_plural': 'RegistrarUsuarios'},
        ),
        migrations.AlterModelOptions(
            name='registrarusuariogym',
            options={'verbose_name': 'RegistrarUsuarioGym', 'verbose_name_plural': 'RegistrarUsuarioGyms'},
        ),
        migrations.AlterModelOptions(
            name='registrarusuariogymday',
            options={'verbose_name': 'RegistrarUsuarioGymDay', 'verbose_name_plural': 'RegistrarUsuarioGymDays'},
        ),
        migrations.AlterModelTable(
            name='registrarusuario',
            table='RegistrarUsuario',
        ),
        migrations.AlterModelTable(
            name='registrarusuariogym',
            table='RegistrarUsuarioGym',
        ),
        migrations.AlterModelTable(
            name='registrarusuariogymday',
            table='RegistrarUsuarioGymDay',
        ),
    ]
