# Generated by Django 5.1.2 on 2024-11-09 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0002_alter_registrarusuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRenovacion', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('es_renovado', models.BooleanField(default=False)),
                ('usuarioGym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to='gimnasioApp.registrarusuariogym')),
            ],
        ),
    ]
