# Generated by Django 5.1.2 on 2024-11-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0003_renovacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renovacion',
            options={'verbose_name': 'Renovacion', 'verbose_name_plural': 'Renovaciones'},
        ),
        migrations.AlterModelTable(
            name='renovacion',
            table='Renovacion',
        ),
    ]
