# Generated by Django 5.1.2 on 2024-11-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0004_alter_renovacion_options_alter_renovacion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarusuariogym',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
